name: Daily Website Screenshot to WhatsApp

on:
  schedule:
    - cron: "0 8 * * *" # Every day at 8 AM UTC
  workflow_dispatch:

jobs:
  capture:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run screenshot script
        run: node scripts/screenshot.js
        env:
          WEBSITE_USER: ${{ secrets.WEBSITE_USER }}
          WEBSITE_PASS: ${{ secrets.WEBSITE_PASS }}
          GMAIL_CLIENT_ID: ${{ secrets.GMAIL_CLIENT_ID }}
          GMAIL_CLIENT_SECRET: ${{ secrets.GMAIL_CLIENT_SECRET }}
          GMAIL_REFRESH_TOKEN: ${{ secrets.GMAIL_REFRESH_TOKEN }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}

      - name: Upload screenshot artifact
        uses: actions/upload-artifact@v4
        with:
          name: homepage-screenshot
          path: homepage.png
          retention-days: 7

  send:
    runs-on: ubuntu-latest
    needs: capture
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: homepage-screenshot
          path: .

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Send screenshot via WhatsApp
        run: node scripts/send-whatsapp.js
        env:
          TWILIO_SID: ${{ secrets.TWILIO_SID }}
          TWILIO_AUTH: ${{ secrets.TWILIO_AUTH }}
          WHATSAPP_FROM: ${{ secrets.WHATSAPP_FROM }}
          WHATSAPP_TO: ${{ secrets.WHATSAPP_TO }}
